### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Landyncai** [withfig/fig#1261]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

I followed the steps to execute the npm run dev command and got the following error, the previous steps to execute npm install did not have any problems.

Welcome to Fig Dev Mode

 1. Edit your spec(s) in the src/ directory
 2. On save, they will compile to the local build/ directory
 3. Test your changes instantly in your terminal
 4. When done, hit ctrl + c to exit

Error setting setting:
defaults read failed
Error setting setting:
defaults read failed
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/landyn/.fig/logs/specs.log'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at Command.<anonymous> (/Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:99:34)
    at step (/Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:33:23)
    at Object.next (/Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:14:53)
    at /Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:4:12)
    at Command.runProgram (/Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:71:12)
    at Command.listener [as _actionHandler] (/Users/landyn/IdeaProjects/landyn/fig-autocomplete/node_modules/commander/lib/command.js:488:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/landyn/.fig/logs/specs.log'
}

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.56 (B421) [Dev] [ABC]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/landyn/.local/bin:/Users/landyn/.fig/bin:/Users/landyn/.local/bin:/Users/landyn/.local/bin:/Users/landyn/.oh-my-zsh/custom/plugins/fzf-zsh-plugin/bin:/Users/landyn/.fzf/bin:/Users/landyn/Documents/Apps/maven/apache-maven-3.6.3/bin:/Users/landyn/Documents/Apps/gradle/gradle-2.6/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,2
  - Chip: Apple M1 Max
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 64 GB
## OS Info:
  - macOS 12.3.1 (21E258)
## Environment:
  - User Shell: /bin/zsh
  - Current Directory: /Users/landyn
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 7170/% (com.googlecode.iterm2)
  - Active Process: zsh (53720) - /dev/ttys001
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:DE1F229A-FE20-4487-9A58-02A17F6844F8
    - PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/landyn/.local/bin:/Users/landyn/.fig/bin:/Users/landyn/.local/bin:/Users/landyn/.local/bin:/Users/landyn/.oh-my-zsh/custom/plugins/fzf-zsh-plugin/bin:/Users/landyn/.fzf/bin:/Users/landyn/Documents/Apps/maven/apache-maven-3.6.3/bin:/Users/landyn/Documents/Apps/gradle/gradle-2.6/bin
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.3.0
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: application is not present.
  - Docker: false
```

**Comment by mschrage** [comment]
Hey @Landyncai, thanks for reporting this. I think this is a bug with our dev environment. @fedeci can you investigate?

**Comment by lonrun** [comment]
Welcome to Fig Dev Mode

 1. Edit your spec(s) in the src/ directory
 2. On save, they will compile to the local build/ directory
 3. Test your changes instantly in your terminal
 4. When done, hit ctrl + c to exit

Error setting setting:
defaults read failed
Error setting setting:
defaults read failed
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/cyz/.fig/logs/specs.log'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2170:35)
    at Command.<anonymous> (/Users/cyz/widgets/autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:99:34)
    at step (/Users/cyz/widgets/autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:33:23)
    at Object.next (/Users/cyz/widgets/autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:14:53)
    at /Users/cyz/widgets/autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cyz/widgets/autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:4:12)
    at Command.runProgram (/Users/cyz/widgets/autocomplete/node_modules/@withfig/autocomplete-tools/build/scripts/dev.js:71:12)
    at Command.listener [as _actionHandler] (/Users/cyz/widgets/autocomplete/node_modules/commander/lib/command.js:488:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/cyz/.fig/logs/specs.log'
}

Node.js v17.8.0

**Comment by lonrun** [comment]
> 

I also encounter this issue.

**Comment by fedeci** [comment]
Fixed in the latest autocomplete-tools, you can run `rm -r node_modules && npm i` to get it working!
Thanks for reporting this issue @lonrun @Landyncai
