### ISSUE TITLE
Fig errors (unknown cause, perhaps due to computer going to sleep)

### ISSUE THREAD

**Issue by adamAtSlync** [withfig/fig#1379]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
After my computer goes to sleep (I think this is the cause), fig stops working and I get this error in every shell/terminal:
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Error with `RUST_BACKTRACE=1`
```
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: std::io::stdio::_print
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: fig::cli::Cli::execute::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::park::thread::CachedParkThread::block_on
   7: tokio::runtime::thread_pool::ThreadPool::block_on
   8: tokio::runtime::Runtime::block_on
   9: fig::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Error with `RUST_BACKTRACE=full` 
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
stack backtrace:
   0:        0x105b6bcc2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
   1:        0x105b9256b - core::fmt::write::hb68c3045179d0cad
   2:        0x105b6293e - std::io::Write::write_fmt::haf84c797e63d79f0
   3:        0x105b6e760 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
   4:        0x105b6e446 - std::panicking::default_hook::ha3efe84526f027fa
   5:        0x105b6eefb - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
   6:        0x105b6ebe3 - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
   7:        0x105b6c157 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
   8:        0x105b6e8aa - _rust_begin_unwind
   9:        0x105bcd653 - core::panicking::panic_fmt::hf7d6e5207e013f69
  10:        0x105b61948 - std::io::stdio::_print::hf472889da30bc373
  11:        0x10517d475 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7f6736d0cbba5fa7
  12:        0x105129b09 - fig::cli::Cli::execute::{{closure}}::h928e261762edc88d
  13:        0x105184fe9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8df661b0c1d05059
  14:        0x1050374ac - tokio::park::thread::CachedParkThread::block_on::hb9dadf20e3a96a7e
  15:        0x1050c5079 - tokio::runtime::thread_pool::ThreadPool::block_on::hb251f67d1fda3190
  16:        0x10508fed1 - tokio::runtime::Runtime::block_on::h75075f7c50ae7a52
  17:        0x104f50f52 - fig::main::h143f14cbccab4216
  18:        0x104f84b36 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0b97fc1b6af23f58
  19:        0x10508ef7c - std::rt::lang_start::{{closure}}::hf217a4bec99e392a
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.1|Version 1.0.57 (B439)|/usr/local/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.57 (B439) [Canadian English] 
UserShell: /usr/local/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ascott/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true 
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: <generated dynamically>
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: 57293/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by adamAtSlync** [comment]
@mschrage it's whenever I run any command, sorry should have included that!

**Comment by mschrage** [comment]
Thanks for the quick response @adamAtSlync! Are you free to jump on a call quickly to debug? https://calendly.com/mschrage/30min

**Comment by mschrage** [comment]
Can you do the following debugging steps:
1. What terminal are you using? Does this issue occur in other terminals?
2. What shell are you using? Does this issue occur in other shells?
3. If you launch a new terminal session, does the issue still occur?
4. Can you share a screen recording of the issue?

**Comment by adamAtSlync** [comment]
@mschrage I'm not able to reliably repro, so I'll get back to you as soon as I hit it again (so far I've run into it a few times at the start of the work day so it might have to do with putting my computer to sleep for an extended period of time)

**Comment by adamAtSlync** [comment]
@mschrage this has happened again, let me know if you want to try and hop on a call to look at it
