### ISSUE TITLE
`index out of bounds: index is 18446744073709551615` in IntelliJ terminal

### ISSUE THREAD

**Issue by WaveWalkerMe** [withfig/fig#1570]
### Description:
Hi Fig Team,

I am facing some issues with opening the Terminal in Intellij. Sometimes when I  open it, I receive this error. Most of the times if I close the Terminal and open it again it starts working, but not all of the times.

Error:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /Users/ciaccount/actions-runner/_work/macos/macos/rust-lib/alacritty_terminal/src/grid/storage.rs:98:23
                             note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

#### Fig details:
  - Fig version: Version 1.0.58 (B463) [German]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: <generated dynamically>
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
#### Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro15,1
  - Chip: 
  - Cores: 6
  - Memory: 32 GB
#### OS Info:
  - macOS 12.4.0 (21F79)
#### Environment:
  - User Shell: /bin/zsh
  - CLI Installed: true
  - Executable Location: /usr/local/bin/fig
  - Current Window ID: 17168/% (com.jetbrains.intellij)
  - Active Process: zsh (77514) - /dev/ttys007
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=364ba407-9e7a-4ba8-b665-4873d05a6018
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM=1
    - FIG_TERM_VERSION=4.4.0
    - FIG_PID=77514
#### Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: true

Best regards,
Adrian

**Comment by SeparateRecords** [comment]
@WaveWalkerMe thank you for the report! I believe this is something @grant0417 will want to look into. 

For now, do you have any concrete steps to reproduce? What specific IntelliJ version are you running? And would you be able to send us your zshrc? (hello@fig.io if you don't want to share publicly)

**Comment by WaveWalkerMe** [comment]
@SeparateRecords thanks for the update. I am using Intellij IDEA Ultimate - 2022.1.3 (last version).

My .zshrc has alot of aliases i use for personal or project related use. The parts i use for fig are this ones:

```
# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"

.... other settings and aliases

# Fig
#############################################

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
```

**Comment by SeparateRecords** [comment]
Actually it's specifically the aliases/settings that I'm interested in! It's possible that there's some kind of weird interaction happening that causes this failure. We've seen a similar bug before but never knew anyone that could actually reproduce it!

**Comment by SeparateRecords** [comment]
Could you schedule a time with Grant? He's super excited to fix this! https://calendly.com/grant-fig/30min

**Comment by WaveWalkerMe** [comment]
Unfortunately I wasn't able to reproduce it, but it also never happend since I reported it. That's why I thought that a meeting won't help that much

**Comment by grant0417** [comment]
Going to close this issue for now then since it can not be repro, but if you are able to reproduce or have any other details that could help please let us know @WaveWalkerMe

**Comment by bendh** [comment]
Was googling when stumbled with the same error: 
/ciaccount/actions-runner/_work/macos/macos/rust-lib/alacritty_terminal/src/term/mod.rs:1281:24
                                                                                                                                                                                                          note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Restarting intelij fixed this for me. I think that this happends when having the mac sleeping and wakening multiple times trigger this. See this also happening with other plugins.

**Comment by SeparateRecords** [comment]
@bendh Next time this happens to you can you try adding `export RUST_BACKTRACE=full` to the very top of your shell config? We still don't have good visibility into what's causing this so any help is good!

If you can reproduce it reliably then definitely get in touch! https://calendly.com/grant-fig/30min

**Comment by Plytas** [comment]
Does this help? Started happening to me today. Also, only happens if I open a new terminal tab manually (clicking with a mouse), opens fine if I use a keyboard shortcut.

PhpStorm 2023.1 EAP
Build #PS-231.5920.17, built on January 30, 2023

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /Users/distiller/project/desktop/lib/alacritty_terminal/src/grid/mod.rs:467:14
stack backtrace:
0:        0x102c88d24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2990a6f24ccff6db
1:        0x1026eff44 - core::fmt::write::h91497fd291c8b104
2:        0x102c83c10 - std::io::Write::write_fmt::h23fa41342cffacf4
3:        0x102c8ced0 - std::panicking::default_hook::{{closure}}::hb41cdb784f4c17ac
4:        0x102c8cc18 - std::panicking::default_hook::hdfe992d5fb29a991
5:        0x102c8d46c - std::panicking::rust_panic_with_hook::h2eb0e4b718773521
6:        0x102c8d318 - std::panicking::begin_panic_handler::{{closure}}::h06a693206403b4d5
7:        0x102c8b654 - std::sys_common::backtrace::__rust_end_short_backtrace::h8998defd518dbcad
8:        0x102c8d0b4 - _rust_begin_unwind
9:        0x102e98824 - core::panicking::panic_fmt::ha46aa9af97eb193d
10:        0x102e98794 - core::panicking::panic_bounds_check::h1dcb29c14d8acf38
11:        0x10280b500 - <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::input::h5829abade8f01e33
12:        0x1028a7ea4 - vte::Parser::perform_action::hc28fb1bfe918c359
13:        0x1028eff6c - figterm::figterm_main::{{closure}}::h99ab06ccc132c8af
14:        0x102910294 - tokio::runtime::park::CachedParkThread::block_on::h5af46967b0cbe507
15:        0x102814ef0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h2bfcd33e06ff2205
16:        0x102883298 - tokio::runtime::runtime::Runtime::block_on::h0e6503061d56c3ba
17:        0x1028f96ac - figterm::main::h927762ad1dd3d177
18:        0x102841d94 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha825b43327e9c9cb
19:        0x10280bfcc - std::rt::lang_start::{{closure}}::h60741e80e4f629f6
20:        0x102c7f118 - std::rt::lang_start_internal::h94fa211da9d06d56
21:        0x1028fd2a4 - _main
```

**Comment by heychazza** [comment]
> Does this help? Started happening to me today. Also, only happens if I open a new terminal tab manually (clicking with a mouse), opens fine if I use a keyboard shortcut.
> 
> PhpStorm 2023.1 EAP Build #PS-231.5920.17, built on January 30, 2023
> 
> ```
> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', /Users/distiller/project/desktop/lib/alacritty_terminal/src/grid/mod.rs:467:14
> stack backtrace:
> 0:        0x102c88d24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2990a6f24ccff6db
> 1:        0x1026eff44 - core::fmt::write::h91497fd291c8b104
> 2:        0x102c83c10 - std::io::Write::write_fmt::h23fa41342cffacf4
> 3:        0x102c8ced0 - std::panicking::default_hook::{{closure}}::hb41cdb784f4c17ac
> 4:        0x102c8cc18 - std::panicking::default_hook::hdfe992d5fb29a991
> 5:        0x102c8d46c - std::panicking::rust_panic_with_hook::h2eb0e4b718773521
> 6:        0x102c8d318 - std::panicking::begin_panic_handler::{{closure}}::h06a693206403b4d5
> 7:        0x102c8b654 - std::sys_common::backtrace::__rust_end_short_backtrace::h8998defd518dbcad
> 8:        0x102c8d0b4 - _rust_begin_unwind
> 9:        0x102e98824 - core::panicking::panic_fmt::ha46aa9af97eb193d
> 10:        0x102e98794 - core::panicking::panic_bounds_check::h1dcb29c14d8acf38
> 11:        0x10280b500 - <alacritty_terminal::term::Term<T> as alacritty_terminal::ansi::Handler>::input::h5829abade8f01e33
> 12:        0x1028a7ea4 - vte::Parser::perform_action::hc28fb1bfe918c359
> 13:        0x1028eff6c - figterm::figterm_main::{{closure}}::h99ab06ccc132c8af
> 14:        0x102910294 - tokio::runtime::park::CachedParkThread::block_on::h5af46967b0cbe507
> 15:        0x102814ef0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h2bfcd33e06ff2205
> 16:        0x102883298 - tokio::runtime::runtime::Runtime::block_on::h0e6503061d56c3ba
> 17:        0x1028f96ac - figterm::main::h927762ad1dd3d177
> 18:        0x102841d94 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha825b43327e9c9cb
> 19:        0x10280bfcc - std::rt::lang_start::{{closure}}::h60741e80e4f629f6
> 20:        0x102c7f118 - std::rt::lang_start_internal::h94fa211da9d06d56
> 21:        0x1028fd2a4 - _main
> ```

Facing same issue, only happened since PHPStorm 2023

**Comment by clo4** [comment]
Paging @grant0417 ;)
