### ISSUE TITLE
@fig/complete-commander doesn't work with custom help command

### ISSUE THREAD

**Issue by bradgarropy** [withfig/fig#1745]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and tested again (tell us if that fixed it)

### Description:

I'm running a `commander` program as defined below. When running `generateCompletionSpec`, I get an error in regards to parsing the `help` command, which I have modified slightly with `addHelpCommand('help', 'show help')`.

```
import { Command } from 'commander';
import { version } from '../package.json';
import { generateCompletionSpec } from '@fig/complete-commander';
import path from 'path';
import { writeFileSync } from 'fs';

const program = new Command();

program.name('trello');
program.description('Trello Developer CLI');
program.version(version, '-v, --version');
program.addHelpCommand('help', 'show help');

program
  .command('autocompletions', { hidden: true })
  .description('generate fig spec')
  .action(() => {
    const spec = generateCompletionSpec(program);

    if (!spec) {
      return;
    }

    const specPath = path.join(__dirname, '..', 'autocompletions', 'trello.ts');

    writeFileSync(specPath, spec);
  });

program.parse(process.argv);
```

I get the following error.

```
bgarropy@C02G71HDMD6V web % npx trello autocompletions
/Users/bgarropy/projects/web/node_modules/@fig/complete-commander/lib/index.js:83
            name: _helpCommandnameAndArgs.split(" ")[1].slice(1, -1),
                                                       ^
TypeError: Cannot read properties of undefined (reading 'slice')
    at helpSubcommand (/Users/bgarropy/projects/web/node_modules/@fig/complete-commander/lib/index.js:83:56)
    at generateCommand (/Users/bgarropy/projects/web/node_modules/@fig/complete-commander/lib/index.js:114:38)
    at generateCommand (/Users/bgarropy/projects/web/node_modules/@fig/complete-commander/lib/index.js:109:32)
    at generateCompletionSpec (/Users/bgarropy/projects/web/node_modules/@fig/complete-commander/lib/index.js:133:30)
    at Command.<anonymous> (/Users/bgarropy/projects/web/packages/dev-cli/src/cli.ts:23:70)
    at Command.listener [as _actionHandler] (/Users/bgarropy/projects/web/node_modules/commander/lib/command.js:473:17)
    at /Users/bgarropy/projects/web/node_modules/commander/lib/command.js:1173:65
    at Command._chainOrCall (/Users/bgarropy/projects/web/node_modules/commander/lib/command.js:1091:12)
    at Command._parseCommand (/Users/bgarropy/projects/web/node_modules/commander/lib/command.js:1173:27)
    at Command._dispatchSubcommand (/Users/bgarropy/projects/web/node_modules/commander/lib/command.js:998:25)
```

Seems like the `helpSubcommand` didn't take into account for some of the custom help modifications that `commander` allows. Let me know and I can provide more information for you guys!

### Environment

```yaml
bgarropy@C02G71HDMD6V web % fig diagnostic
fig-details:
  - desktop-version: Version 1.0.61 (B518) [U.S.]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro16,1
  - chip-id: 
  - cores: 6
  - mem: 32 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/bgarropy/projects/web
  - exe-path: /usr/local/bin/fig
  - install-method: brew
  - env-vars:
    - FIG_INTEGRATION_VERSION: 8
    - FIG_PID: 93809
    - FIG_TERM: 1
    - FIG_TERM_VERSION: 5.1.0
    - PATH: /Users/bgarropy/.nvm/versions/node/v16.17.0/bin:/Users/bgarropy/.yvm/shim:/Users/bgarropy/.nvm/versions/node/v16.14.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bgarropy/.yvm/shim:/Users/bgarropy/.nvm/versions/node/v16.14.0/bin:/Users/bgarropy/.fig/bin:/Users/bgarropy/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - TERM_SESSION_ID: B1FDD501-CBCE-49EE-A73B-E04B975ECC8C
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: application is not present.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```
```

**Comment by fedeci** [comment]
Hi @bradgarropy, which veraion of commander are you using?

**Comment by bradgarropy** [comment]
@fedeci I'm using `commander` version `8.1.0`.
