### ISSUE TITLE
bug: Access is allowed from Event Dispatch Thread (EDT) only

### ISSUE THREAD

**Issue by Jesse0716** [withfig/fig#2469]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

Mac

### Expected behaviour

When we open IntelliJ IDEA, we get an IDE internal error, but the Fig plugin works

### Actual behaviour

Access is allowed from Event Dispatch Thread (EDT) only

java.lang.RuntimeException: Cannot invoke (class=FigWindowListener, method=toolWindowsRegistered, topic=tool window events)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy1/jdk.proxy1.$Proxy94.toolWindowsRegistered(Unknown Source)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing(ToolWindowSetInitializer.kt:155)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing$default(ToolWindowSetInitializer.kt:152)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:138)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:45)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$1.invokeSuspend(ToolWindowSetInitializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Current thread: Thread[DefaultDispatcher-worker-18,5,main] 362949661 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 858593847
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1050)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1037)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1280)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1274)
	at com.intellij.toolWindow.ToolWindowHeader.setTabActions(ToolWindowHeader.kt:293)
	at com.intellij.toolWindow.InternalDecoratorImpl.setTabActions(InternalDecoratorImpl.kt:432)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setTabActions(ToolWindowImpl.kt:357)
	at org.jetbrains.plugins.terminal.TerminalToolWindowManager.initToolWindow(TerminalToolWindowManager.java:142)
	at org.jetbrains.plugins.terminal.TerminalToolWindowFactory.createToolWindowContent(TerminalToolWindowFactory.java:30)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:421)
	at io.fig.jetbrains.FigService.initContentManager(FigService.java:45)
	at io.fig.jetbrains.FigWindowListener.toolWindowsRegistered(FigWindowListener.java:22)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:644)
	... 16 more
<img width="1512" alt="截屏2023-04-14 17 22 45" src="https://user-images.githubusercontent.com/95994183/232005239-5e141788-22d1-4274-ae23-9d9d7e53b004.png">

### Steps to reproduce

I can reproduce this error, just open IntelliJ IDEA and it will appear

### Environment

```yaml
fig-details:
  - 2.15.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1 Pro
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.2.1 (22D68)
environment:
  - shell: /bin/zsh
  - terminal: intellij-idea-ultimate
  - cwd: /Users/newcreation/IdeaProjects/ruoyi-vue-pro
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: 47c0f57f-8375-4385-895e-939c9f69eecf
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/newcreation/.nvm/versions/node/v19.0.1/bin:/Users/newcreation/miniforge3/bin:/Users/newcreation/miniforge3/condabin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/usr/local/maven/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.jetbrains.intellij
    - FIG_PID: 68179
    - FIG_SET_PARENT: 47c0f57f-8375-4385-895e-939c9f69eecf
```

**Comment by MasatoshiTada8888** [comment]
I have same issue on IntelliJ UE 2023.1

```
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Licensed to Masatoshi Tada
You have a perpetual fallback license for this version.
Subscription is active until March 30, 2024.
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    AWSCloudFormation (231.8109.91)
    some.awesome (1.14)
    org.intellij.plugins.hcl (231.8109.91)
    com.jetbrains.CyanTheme (1.3)
    name.kropp.intellij.makefile (231.8109.91)
    dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
    io.fig.jetbrains (2.0.0)
    CheckStyle-IDEA (5.78.0)
    com.samuraism.plugins.mito (2023.1.2)
    aws.toolkit (1.65-231)

Kotlin: 231-1.8.20-IJ8109.175
```

```
$ fig diagnostic

fig-details:
  - 2.15.0
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Pro
  - cores: 10
  - mem: 32.00 GB
os-info:
  - macOS 13.3.1 (22E261)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/tada
  - exe-path: /opt/homebrew/bin/fig
  - install-method: brew
  - env-vars:
    - FIGTERM_SESSION_ID: d7503ed9-5b32-44ee-ae7f-394514013ce9
    - FIG_SET_PARENT_CHECK: 1
    - FIG_TERM: 2.15.0
    - PATH: /Users/tada/.rd/bin:/opt/homebrew/opt/python@3.10/bin:/Users/tada/apache-maven-3.8.3/bin:/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.3.0/Contents/Home/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/tada/.fig/bin:/Users/tada/.local/bin:/Users/tada/Library/Application Support/JetBrains/Toolbox/scripts
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - __CFBundleIdentifier: com.googlecode.iterm2
    - FIG_PID: 28756
```

**Comment by mschrage** [comment]
I can't seem to reproduce. Here is the source for the [JetBrains extension](https://github.com/withfig/jetbrains-extension). Perhaps you can debug locally?

**Comment by LetianLi** [comment]
It looks like the jetbrains extension got deleted? Can't find the source and it's no longer in the plugin marketplace.

**Comment by Ragura** [comment]
Also having the same issue with the same error message upon opening PyCharm 2023.1.

**Comment by jimmyn** [comment]
I have same issue on WebStorm 2023.1.2

```
Build #WS-231.9011.35, built on May 16, 2023
Licensed to Dmitriy Nevzorov
Subscription is active until November 28, 2023.
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true
    jest.test.tree.use.jasmine.reporter=false

Non-Bundled Plugins:
    quokka.js (1.0.388)
    AWSCloudFormation (231.8109.91)
    com.github.copilot (1.2.6.2594)
    com.intellij.apacheConfig (231.9011.41)
    io.fig.jetbrains (2.0.0)
    zielu.gittoolbox (500.0.8+213)
    com.intellij.lang.jsgraphql (4.0.1)
```

Here is the stack trace:

```
Access is allowed from Event Dispatch Thread (EDT) only

java.lang.RuntimeException: Cannot invoke (class=FigWindowListener, method=toolWindowsRegistered, topic=tool window events)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy1/jdk.proxy1.$Proxy71.toolWindowsRegistered(Unknown Source)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing(ToolWindowSetInitializer.kt:155)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing$default(ToolWindowSetInitializer.kt:152)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:138)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:45)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$1.invokeSuspend(ToolWindowSetInitializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Current thread: Thread[DefaultDispatcher-worker-15,5,main] 1074578280 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1278275088
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1050)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1037)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1280)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1274)
	at com.intellij.toolWindow.ToolWindowHeader.setTabActions(ToolWindowHeader.kt:293)
	at com.intellij.toolWindow.InternalDecoratorImpl.setTabActions(InternalDecoratorImpl.kt:432)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setTabActions(ToolWindowImpl.kt:357)
	at org.jetbrains.plugins.terminal.TerminalToolWindowManager.initToolWindow(TerminalToolWindowManager.java:142)
	at org.jetbrains.plugins.terminal.TerminalToolWindowFactory.createToolWindowContent(TerminalToolWindowFactory.java:30)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:421)
	at io.fig.jetbrains.FigService.initContentManager(FigService.java:45)
	at io.fig.jetbrains.FigWindowListener.toolWindowsRegistered(FigWindowListener.java:22)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:644)
	... 16 more

```

**Comment by jimmyn** [comment]
Any update here? This is a very annoying issue.

**Comment by jimmyn** [comment]
Bump. Had to disable fig plugin until this is fixed

**Comment by AlexMRuch** [comment]
I'm also having this issue on PyCharm 2023.1.2 Build #PY-231.9011.38 on Mac Ventura 13.4 (22F66).

**Comment by ollie-stytch** [comment]
Bump, disabled fig plugin for now.

**Comment by jimmyn** [comment]
Any update here?

**Comment by gmuench** [comment]
Still failing with copilot 

PyCharm 2023.3 - Build #PY-233.11799.259, built on December 3, 2023
GitHub Copilot1.4.5.4049
