### ISSUE TITLE
bug: java.lang.RuntimeException: Cannot invoke (class=FigWindowListener, method=toolWindowsRegistered, topic=tool window events)

### ISSUE THREAD

**Issue by scannerGT** [withfig/fig#2676]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macOS 13.5.0 (22G74)

### Expected behaviour

Properly run without errors in  current PHPStorm

### Actual behaviour

PHPStorm on start reports always Exception in plugin Fig (2.0.0)

### Steps to reproduce

Intergrate Fig with PHPStorm and run IDE.

IDE version: PHPStorm 2023.2 and earlier.

IDE reports:

----- stracktrace.txt

java.lang.RuntimeException: Cannot invoke (class=FigWindowListener, method=toolWindowsRegistered, topic=tool window events)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy2/jdk.proxy2.$Proxy80.toolWindowsRegistered(Unknown Source)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing(ToolWindowSetInitializer.kt:160)
	at com.intellij.toolWindow.ToolWindowSetInitializer.postEntryProcessing$default(ToolWindowSetInitializer.kt:157)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:143)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:46)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$1.invokeSuspend(ToolWindowSetInitializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[DefaultDispatcher-worker-20,5,main] 871196084 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 890811472
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1066)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1283)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1277)
	at com.intellij.toolWindow.ToolWindowHeader.setTabActions(ToolWindowHeader.kt:276)
	at com.intellij.toolWindow.InternalDecoratorImpl.setTabActions(InternalDecoratorImpl.kt:431)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setTabActions(ToolWindowImpl.kt:359)
	at org.jetbrains.plugins.terminal.TerminalToolWindowManager.initToolWindow(TerminalToolWindowManager.java:142)
	at org.jetbrains.plugins.terminal.TerminalToolWindowFactory.createToolWindowContent(TerminalToolWindowFactory.java:30)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:554)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:423)
	at io.fig.jetbrains.FigService.initContentManager(FigService.java:45)
	at io.fig.jetbrains.FigWindowListener.toolWindowsRegistered(FigWindowListener.java:22)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:663)
	... 16 more

### Environment

```yaml
fig-details:
  - 2.16.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.5.0 (22G74)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /bin/zsh
```

**Comment by segrey** [comment]
Here is the issue in the IntelliJ repo: [IDEA-328086](https://youtrack.jetbrains.com/issue/IDEA-328086/Fig.io-breaks-the-built-in-terminal). Likely, the Fig plugin version 2.0.0 will be marked as broken. Please release the fix with incremented version to pass broken plugins defense.
