### ISSUE TITLE
Installation errors when dotfiles don't exist or are not the expected filetype

### ISSUE THREAD

**Issue by mschrage** [withfig/fig#802]
![image](https://user-images.githubusercontent.com/3155109/150247253-28ae7e89-7478-4f61-9af6-651c9d16813f.png)

```
❯ fig doctor

Let's make sure Fig is running...

✅ Fig bin exists
✅ Fig in PATH
✅ Fig is running

Let's check your dotfiles...

✅ Fig ENV variables are in ~/.profile
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
fig-cli/cmd/doctor.NewCmdDoctor.func1(0xc00019c000, {0x14abb7c, 0x0, 0x0})
/Users/runner/work/macos/macos/figcli2/cmd/doctor/doctor.go:182 +0x550f
github.com/spf13/cobra.(*Command).execute(0xc00019c000, {0x189edb8, 0x0, 0x0})
/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1866060)
/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
fig-cli/cmd/root.Execute()
/Users/runner/work/macos/macos/figcli2/cmd/root/root.go:325 +0x611
main.main()
/Users/runner/work/macos/macos/figcli2/main.go:12 +0x85
```

> So interestingly `~/.zprofile` does not exist on my machine (as a directory nor file).

**Comment by SeparateRecords** [comment]
This panic also happens when the fig source lines are commented out, easy to reproduce

**Comment by mschrage** [comment]
Something to look into @grant0417 👀

**Comment by grant0417** [comment]
This should be fixed in next build.
